[build]
  functions = "."
  publish = "../"

[build.environment]
  AIRTABLE_API_KEY = "patNFxvLmjoRkO7ye.ac8cf41671cc9b6e33d8d7a00432f9b29a10c998e087eb0f93165c433b22f0d1"
  AIRTABLE_BASE_ID = "applXM3jxKfBUaIOE"
  ADMIN_PASSWORD = "1244"

[functions]
  directory = "."
